project:
  name: quickstart-cisco-duo-network-gateway
  owner: quickstart-eng@amazon.com
  regions:
  - us-east-1
tests:
   test-full:
    template: ./templates/quickstart-cisco-duo-network-gateway-master.yaml
    s3_bucket: tcat-quickstart-cisco-duo-net3cnfvoir
    parameters:
      QSS3BucketName: $[taskcat_autobucket]
      QSS3BucketRegion: $[taskcat_current_region]
      KeyPairName: /Users/muffadal/.ssh/id_rsa
      RemoteAccessCIDR: "10.0.0.0/16"
      AvailabilityZones: $[taskcat_getaz_2]
      RedisAuth: redis-auth-token
      RedisCacheNodeType: cache.t3.medium
      RedisEngineVersion: 3.2.6
      NumShards: 1
      NumReplicas: 1
      SnapshotName: ''
      SnapshotRetentionLimit: 35
      AdminServerInstanceType: c5.large
      PortalServerInstanceType: c5.xlarge
      PortalServerName: PortalServer
      RedisPort: 6379
      RedisAuth: redis-auth-token
      EmailAddress: muffadalq@gmail.com
   test-adminserver:
    template: ./templates/admin-server.yaml
    regions:
    - us-east-1
    parameters:
      KeyPairName: /Users/muffadal/.ssh/id_rsa
      RemoteAccessCIDR: "10.0.0.0/16"
      PrivateSubnet1ID: subnet-00b26c5c1aa3ab0f4
      AdminServerInstanceType: c5.large
      VPCID: vpc-0524c2ce1690c5bae
      RedisHost: master.tcrnhg8ji6jbkqb.sbnped.use1.cache.amazonaws.com
      RedisPort: 6379
      RedisAuth: redis-auth-token
      QSS3KeyPrefix: ''
   test-portalserver-stack:
    template: ./templates/quickstart-cisco-duo-network-gateway-portal-servers.yaml
    regions:
    - us-east-1
    parameters:
      KeyPairName: /Users/muffadal/.ssh/id_rsa
      EmailAddress: muffadalq@gmail.com
      RemoteAccessCIDR: "10.0.0.0/16"
      PrivateSubnet1ID: subnet-00b26c5c1aa3ab0f4
      PrivateSubnet2ID: subnet-0ccdcfc9a51873602
      PublicSubnet1ID: subnet-09bde8d094c068d03
      PublicSubnet2ID: subnet-08487916f435b5912
      QSS3KeyPrefix: ''
      PortalServerInstanceType: c5.xlarge
      VPCCIDR: "10.0.0.0/16"
      VPCID: vpc-0524c2ce1690c5bae
      RedisHost: master.tcrnhg8ji6jbkqb.sbnped.use1.cache.amazonaws.com
      RedisPort: 6379
      RedisAuth: redis-auth-token
      PortalServerName: PortalServer
   test-redis-stack:
    template: ./templates/redis-cluster.yaml
    regions:
    - us-east-1
    parameters:
      RemoteAccessCIDR: "10.0.0.0/16"
      PrivateSubnet1ID: subnet-00b26c5c1aa3ab0f4
      PrivateSubnet2ID: subnet-0ccdcfc9a51873602
      VPCID: vpc-0524c2ce1690c5bae
      RedisAuth: redis-auth-token
      RedisCacheNodeType: cache.t3.medium
      RedisEngineVersion: 3.2.6
      NumShards: 1
      NumReplicas: 1
      SnapshotName: ''
      SnapshotRetentionLimit: 35
   test-vpc-template:
    template: ./submodules/quickstart-aws-vpc/templates/aws-vpc.template.yaml
    regions:
    - us-east-1
    parameters:
      AvailabilityZones: us-east-1a, us-east-1b

