project:
  name: quickstart-cisco-duo-network-gateway
  owner: quickstart-eng@amazon.com
  regions:
  - us-east-1
  - us-east-2
  - us-west-2
  - sa-east-1
  - eu-central-1
  - eu-west-1
  - eu-west-2
  - eu-west-3
  - ap-northeast-1
  - ap-southeast-1
  - ap-southeast-2
  parameters:
    QSS3BucketName: $[taskcat_autobucket]
    QSS3BucketRegion: $[taskcat_current_region]
  s3_bucket: tcat-quickstart-cisco-duo-neth2un0ogu
tests:
  test-adminserver:
    template: templates/admin-server.yaml
    parameters:
      PrivateSubnet1ID: subnet-3d5ee010
      AvailabilityZone: us-east-1b
      RemoteAccessCIDR: 10.0.0.0/16 
      VPCID: vpc-223ac744
      RedisHost: dngcluster.abc1.0001.usw2.cache.amazonaws.com
      RedisPort: 6379
      RedisAuth: redis-auth-token
    regions:
      - us-east-1